[env:m5paper]
platform = espressif32
board = m5stack-fire
framework = arduino
upload_speed = 2000000
monitor_speed = 115200
upload_port = /dev/cu.usbserial-DEVICE_SERIAL
monitor_port = /dev/cu.usbserial-DEVICE_SERIAL
board_build.partitions = default_16MB.csv
extra_scripts = pre:load_env.py
build_flags =
  -std=gnu++17
  -Ofast
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
build_unflags =
  -std=gnu++11
lib_deps =
  m5stack/M5EPD
  bblanchon/ArduinoJson
